#!/bin/python3

import sys

n = int(input())
if n % 2 == 1 or n in range(5, 21): 
#se a divisão de n por 2, o resto for igual a 1, ele é ímpar. e colocou esse range porque o 19 é o ultimo número que dividido por 2 daría 1 número só no quociente e 1 no resto 
    print("Weird")
else:
    print("Not Weird")
    
